# Python for Spatial Analysis
## Second part of the module of GG3209 Spatial Analysis with GIS.
### Notebook to practice NumPy and Pandas - Exercises

---
Dr Fernando Benitez -  University of St Andrews - School of Geography and Sustainable Development - Third Iteration 2024.1 

In [3]:
#pip install nbconvert pip install pyppeteer

In [4]:
#--allow-chromium-download

# Practicing NumPy

## 2.0 
Import numpy under the alias `np`.

In [1]:
# The code goes here
import numpy as np

## 2.1 

Create the following arrays:

* Create an array of 10 ones.

* Create an array of the integers 1 to 20.

* Create a 5 x 5 matrix of ones with a dtype int.

In [2]:
#Code comes here
array1 = np.ones(10, dtype=int)
array2 = np.arange(1,21, dtype=int)
array3 = np.ones((5,5))
print(array1)
print(array2)
print(array3)

[1 1 1 1 1 1 1 1 1 1]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


## 2.2 
Use numpy to:
1. Create an 3D matrix of 3 x 3 x 3 full of random numbers drawn from a standard normal distribution (hint: `np.random.randn()`)
2. Reshape the above array into shape (27,)

In [3]:
# Code comes here
arr = np.random.randn(3,3,3)
print(arr)
arr_reshape = np.reshape(arr, 27,)
print(arr_reshape)

[[[ 0.79436561  1.12712574  1.00778028]
  [ 0.49895563  0.15212227 -0.02881244]
  [-0.26484941 -2.9251577  -0.83691904]]

 [[ 0.11642384 -1.09226663 -0.22385569]
  [ 1.14618234  1.28487207 -1.16745415]
  [-1.22596273  0.60625191 -1.20631861]]

 [[-2.04253638  0.03241673 -0.46406215]
  [ 0.29280411  0.6940632  -1.78668386]
  [ 0.24597619 -0.27862682  0.07081589]]]
[ 0.79436561  1.12712574  1.00778028  0.49895563  0.15212227 -0.02881244
 -0.26484941 -2.9251577  -0.83691904  0.11642384 -1.09226663 -0.22385569
  1.14618234  1.28487207 -1.16745415 -1.22596273  0.60625191 -1.20631861
 -2.04253638  0.03241673 -0.46406215  0.29280411  0.6940632  -1.78668386
  0.24597619 -0.27862682  0.07081589]


# 2.3 

Create an array of 20 linearly spaced numbers between 1 and 10.

In [4]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

## 2.4

Run the following code to create an array of shape 4 x 4 and then use indexing to produce the outputs shown below.

In [5]:
import numpy as np
a = np.arange(1, 26).reshape(5, -1)
print(a)
print(a[3, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
20


In [ ]:
20

In [6]:
print(a[1:, 3:])

[[ 9 10]
 [14 15]
 [19 20]
 [24 25]]


```python
array([[ 9, 10],
       [14, 15],
       [19, 20],
       [24, 25]])
```

In [7]:
print(a[1, 0:])

[ 6  7  8  9 10]


```python
array([ 6,  7,  8,  9, 10])
```

In [ ]:
# Code comes here

## 2.5 

Calculate the sum of all the numbers in `a`.

In [8]:
print(np.sum(a))

325


In [9]:
print(np.sum(a[1:,3])) #this would add up all the numbers in a certain part of the array

66


## 2.6 

Calculate the sum of each row in `a`.

In [10]:
print(np.sum(a, axis=1)) #axis = indicates which dimension you want to destroy. Here you wanted to destroy the collums, so you reduce the columns just to row sum.

[ 15  40  65  90 115]


## 2.7 

Extract all values of `a` greater than the mean of `a` (hint: use a boolean mask).

In [11]:
print(np.mean(a))
mask = a > np.mean(a) #this creates a boolean mask
print(a[mask])

13.0
[14 15 16 17 18 19 20 21 22 23 24 25]


# Practicing Pandas

## 2.8

In this set of practice exercises we'll be investigating the carbon footprint of different foods. 

We'll be leveraging a dataset compiled by [Kasia Kulma](https://r-tastic.co.uk/post/from-messy-to-tidy/) and contributed to [R's Tidy Tuesday project](https://github.com/rfordatascience/tidytuesday).

Start by importing pandas with the alias `pd`.

In [26]:
import pandas as pd

## 2.9 

The dataset we'll be working with has the following columns:

|column      |description |
|:-------------|:-----------|
|country       | Country Name |
|food_category | Food Category |
|consumption   | Consumption (kg/person/year) |
|co2_emmission | Co2 Emission (Kg CO2/person/year) |


Import the dataset as a dataframe named `df` from this url: <https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv>

In [27]:
df = pd.read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-02-18/food_consumption.csv")
print(df.head(30))

      country             food_category  consumption  co2_emmission
0   Argentina                      Pork        10.51          37.20
1   Argentina                   Poultry        38.66          41.53
2   Argentina                      Beef        55.48        1712.00
3   Argentina               Lamb & Goat         1.56          54.63
4   Argentina                      Fish         4.36           6.96
5   Argentina                      Eggs        11.39          10.46
6   Argentina        Milk - inc. cheese       195.08         277.87
7   Argentina  Wheat and Wheat Products       103.11          19.66
8   Argentina                      Rice         8.77          11.22
9   Argentina                  Soybeans         0.00           0.00
10  Argentina   Nuts inc. Peanut Butter         0.49           0.87
11  Australia                      Pork        24.14          85.44
12  Australia                   Poultry        46.12          49.54
13  Australia                      Beef        3

## 2.10 

How many rows and columns are there in the dataframe?

In [14]:
df.shape

(1430, 4)

## 2.11

What is the mean `co2_emission` of the whole dataset?

In [15]:
df.co2_emmission.mean()

74.383993006993

## 2.12

What is the maximum `co2_emmission` in the dataset and which food type and country does it belong to?

In [19]:
x = df.co2_emmission.max()
print(x)
df.co2_emmission == x 
print(df.country[df.co2_emmission == x].values) #this is saying, print the country where CO2 emissions are X (previously set X to CO2 max)
print(df.food_category[df.co2_emmission == x].values)#the .values just gives you values, makes it prettier


1712.0
['Argentina']
['Beef']


## 2.13

How many countries produce more than 1000 Kg CO2/person/year for at least one food type?

In [37]:
x = df.co2_emmission > 1000
df.country[x].unique() #the .unique means that you are only showing each country once

array(['Argentina', 'Australia', 'USA', 'Brazil', 'Bermuda'], dtype=object)

## 2.14

Which country consumes the least amount of beef per person per year?


In [79]:
df_beef = df[(df.food_category == "Beef")]
x = df_beef.consumption.min()
df_beef.loc[df_beef.consumption == x].country

1410    Liberia
Name: country, dtype: object

## 2.15

What is the total emissions of all the meat products (Pork, Poultry, Fish, Lamb & Goat, Beef) in the dataset combined?

In [23]:
meat = df[df["food_category"].isin(["Beef", "Pork", "Poultry", "Fish", "Lamb & Goat"])]
meat.consumption.sum()

9015.960000000001

# 2.16 

What is the total emissions of all other (non-meat) products in the dataset combined?

In [29]:
nonmeat = df[~df["food_category"].isin(["Beef", "Pork", "Poultry", "Fish", "Lamb & Goat"])]
nonmeat.consumption.sum()

31181.92

## Well done!

That's all from this week, if you have any questions, do not forget to ask the TAs for assistance.